apiVersion: apps/v1

kind: Deployment

metadata:
  name: react-{{ .Release.Name }}-deployment

spec:
  replicas: 1
  
  selector: 
    matchLabels:
      app: react

  template:
    metadata:
      labels:
        app: react

    spec: 
      containers:
        - name: react
          image: 08129741530/react-img
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: react-{{ .Release.Name }}-configmap 
                  key: REACT_APP_API_URL 

            - name: REACT_APP_LESSON_DAY 
              valueFrom: 
                secretKeyRef: 
                  name: react-{{ .Release.Name }}-secrets 
                  key: REACT_APP_LESSON_DAY 

          ports:
          - containerPort: 3000
  
---

apiVersion: v1

kind: Service

metadata: 
  name: react-{{ .Release.Name }}-service

spec: 
  type: NodePort

  selector:
    app: react
    
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100

