apiVersion: v1

kind: ConfigMap

metadata:
  name: react-{{ .Release.Name }}-configmap

data:
  REACT_APP_API_URL: "http://127.0.0.1:8000"
  
---

apiVersion: v1

kind: Secret

metadata:
  name: react-{{ .Release.Name }}-secrets

type: Opaque

data:
  REACT_APP_LESSON_DAY: ZGF5MQ==